# Generated by Django 5.0.6 on 2024-05-22 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='user',
            new_name='uploader',
        ),
    ]
