# Generated by Django 5.0.6 on 2024-05-22 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_rename_user_videos_uploader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='uploader',
            new_name='user',
        ),
    ]
